### PR TITLE
Translation of Xoops 2.5.9 spanish

### PR DESCRIPTION
**Pull request by osw17**
Translation of Xoops 2.5.9 spanish ready to use
Updated

### CODE REVIEW

**Comment by mambax7** [comment]
Thank you!!!! Gracias!!!

**Comment by mambax7** [comment]
Can you also update the Spanish repository?
https://github.com/XoopsLanguages/spanish

**Comment by mambax7** [comment]
OK, I've added it there:
https://github.com/XoopsLanguages/spanish/tree/master/core/2.5.9

**Comment by osw17** [comment]
Ok Thanks Michael

**Pull request merged**
